<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bookstore.Data</RootNamespace>
    <AssemblyName>Bookstore.Data</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.*" />
    <PackageReference Include="AWSSDK.Rekognition" Version="3.7.*" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.*" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.10.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Domain\Bookstore.Domain.csproj" />
  </ItemGroup>

</Project>
